import type { Metadata } from "next";
import {
  DocSidebar,
  DocSidebarHeading,
  DocSidebarItem,
} from "./Components/DocSidebar";

export const metadata: Metadata = {
  title: "Component Library",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex min-h-screen items-left justify-start bg-zinc-50 font-sans dark:bg-black">
      <DocSidebar>
        <DocSidebarHeading text="hi"></DocSidebarHeading>
        <DocSidebarItem>
          <a href="#">Hey</a>
        </DocSidebarItem>
      </DocSidebar>
    </div>
  );
}
